version: "3.8"
services:
  front:
    build:
      context: ./
    volumes:
      - ./Caddyfile.frontend:/etc/Caddyfile
    command: caddy run -config /etc/Caddyfile
    ports:
      - 8080:80
  back:
    image: caddy:2.4.6
    volumes:
      - ./Caddyfile.backend:/etc/Caddyfile
    command: caddy run -config /etc/Caddyfile
